Fixed checker crash, stuck on some checker errors
```
sqldim/sqldim/src/main/java/com/stealthmountain/sqldim/QueryToOptionalOperator.java:87: error: [assignment.type.incompatible] incompatible types in assignment.
          @NonNull final Optional<T> optional = Optional.ofNullable(item);
                                                                   ^
  found   : @Initialized @NonNull Optional<T[ extends @Initialized @Nullable Object super @Initialized @Nullable Void]>
  required: @UnknownInitialization @NonNull Optional<T[ extends @Initialized @Nullable Object super @Initialized @NonNull Void]>
sqldim/sqldim/src/main/java/com/stealthmountain/sqldim/MarkedQueryToOptionalOperator.java:96: error: [assignment.type.incompatible] incompatible types in assignment.
          @NonNull final Optional<T> optional = Optional.ofNullable(item);
                                                                   ^
  found   : @Initialized @NonNull Optional<T[ extends @Initialized @Nullable Object super @Initialized @Nullable Void]>
  required: @UnknownInitialization @NonNull Optional<T[ extends @Initialized @Nullable Object super @Initialized @NonNull Void]>
2 errors
```